{
 "title": "nginx_overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Accepted connnection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections states",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "Reading" },
    { "expr": "nginx_connections_writing", "legendFormat": "Writing" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}