name: Docker Compose Test

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Validate Prometheus config
        run: |
          curl -sSL https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz | tar -xz
          ./prometheus-2.48.0.linux-amd64/promtool check config ./prometheus/config/prometheus.yml

      - name: Start services
        run: |
          docker compose up -d --build
          sleep 30

      - name: Check containers are running
        run: |
          set -e
          services=("prometheus" "grafana" "nginx" "alertmanager")
          for svc in "${services[@]}"; do
            if docker ps --filter "name=$svc" --format "table {{.Names}}\t{{.Status}}" | grep -q Up; then
              echo "$svc container is running"
            else
              echo "$svc container is not running"
              docker logs "$svc" || true
              exit 1
            fi
          done

      - name: Stop services
        if: always()
        run: docker compose down
