name: Docker Compose Test

on:
push:
branches:
- main
pull_request:
workflow_dispatch:

jobs:
compose-up:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Install docker-compose
    run: |
      apt-get update && apt-get install -y docker-compose

  - name: Build and run docker-compose
    run: |
      docker-compose -f docker-compose.yml up -d --build
      docker-compose ps
      docker-compose down
```
